/**
 * Generate YAML string from AsyncAPI document - Simple version to fix syntax issues
 */
function generateYAML(document: AsyncAPIDocument): string {
  return `# Generated AsyncAPI Specification
asyncapi: ${document.asyncapi}
info:
  title: ${document.info.title}
  version: ${document.info.version}
  description: ${document.info.description ?? ""}

channels:
${Object.entries(document.channels || {})
  .map(
    ([channelPath, channel]) =>
      `  ${channelPath}:
    description: "${channel.description}"
    publish:
      operationId: "${channel.publish?.operationId || ""}"
      description: "${channel.publish?.description || ""}"
      message:
        $ref: "#/components/messages/TestMessage"`,
  )
  .join("\n")}

messages:
${Object.entries(document.messages || {})
  .map(
    ([messageName, message]) =>
      `  ${messageName}:
    description: "${message.description}"
    contentType: "${message.contentType}"
    title: "${message.title}"`,
  )
  .join("\n")}

components:
  schemas:
${Object.entries(document.components?.schemas || {})
  .map(
    ([schemaName, schema]) =>
      `    ${schemaName}:
      type: "${schema.type}"
      properties:
${Object.entries(schema.properties || {})
  .map(
    ([propName, prop]) =>
      `        ${propName}:
          type: "${prop.type}"
          description: "${prop.description || ""}"`,
  )
  .join("\n")}
      required: [${(schema.required || []).map((r) => `"${r}"`).join(", ")}]`,
  )
  .join("\n")}

# AsyncAPI 3.0 generated by @lars-artmann/typespec-asyncapi`;
}
