kind: project
emit:
  - "@typespec/openapi3"
  - "@lars-artmann/typespec-asyncapi"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}/rest"
    openapi-versions:
      - 3.1.0
  "@lars-artmann/typespec-asyncapi":
    emitter-output-dir: "{output-dir}/websocket"
