/**
 * Coverage gate: enforces minimum line coverage for source files.
 * Parses lcov.info (generated by `bun test --coverage`) and fails if
 * any src/*.ts file falls below the threshold.
 *
 * Bun's coverage tracks dist/src/*.js files (loaded by TypeSpec compiler)
 * and some src/*.ts files (imported directly by tests). We remap dist/
 * back to src/ and prefer the higher-coverage entry when both exist.
 */

import { existsSync, readFileSync } from "node:fs";

const MIN_LINE_COVERAGE = 0.75;
const lcovPath = "coverage/lcov.info";

if (!existsSync(lcovPath)) {
  console.error(`Coverage file not found: ${lcovPath}`);
  console.error("Run: bun run test:coverage");
  process.exit(1);
}

const lcov = readFileSync(lcovPath, "utf8");

interface CovData {
  hit: number;
  total: number;
}

const rawEntries = new Map<string, CovData>();
let current: { file: string; total: number; hit: number } | null = null;

for (const line of lcov.split("\n")) {
  if (line.startsWith("SF:")) {
    current = { file: line.slice(3), hit: 0, total: 0 };
  } else if (line.startsWith("DA:")) {
    const hits = Number.parseInt(line.slice(3).split(",")[1] ?? "0", 10);
    if (current) {
      current.total++;
      if (hits > 0) {
        current.hit++;
      }
    }
  } else if (line === "end_of_record" && current && current.total > 0) {
    rawEntries.set(current.file, { hit: current.hit, total: current.total });
    current = null;
  }
}

const srcFiles = new Map<string, CovData>();

for (const [file, cov] of rawEntries) {
  let tsPath: string | null = null;

  if (/^src\/.*\.ts$/.test(file)) {
    tsPath = file;
  } else if (/^dist\/src\/.*\.js$/.test(file)) {
    tsPath = file.replace(/^dist\//, "").replace(/\.js$/, ".ts");
  }

  if (tsPath === null) {
    continue;
  }

  const existing = srcFiles.get(tsPath);
  if (existing) {
    const existingPct = existing.total > 0 ? existing.hit / existing.total : 0;
    const newPct = cov.total > 0 ? cov.hit / cov.total : 0;
    if (newPct > existingPct) {
      srcFiles.set(tsPath, cov);
    }
  } else {
    srcFiles.set(tsPath, cov);
  }
}

const failures: string[] = [];

for (const [file, cov] of srcFiles) {
  const pct = cov.total > 0 ? cov.hit / cov.total : 1;
  const pctStr = (pct * 100).toFixed(1);
  if (pct < MIN_LINE_COVERAGE) {
    const shortName = file.replace(/.*\//, "");
    failures.push(
      `  ${shortName}: ${pctStr}% (min ${MIN_LINE_COVERAGE * 100}%)`,
    );
  }
}

if (failures.length > 0) {
  console.error(
    `\nCoverage gate FAILED — ${failures.length} file(s) below ${MIN_LINE_COVERAGE * 100}%:\n`,
  );
  for (const f of failures) {
    console.error(f);
  }
  console.error(`\nTotal source files checked: ${srcFiles.size}`);
  process.exit(1);
}

const avg =
  srcFiles.size > 0
    ? (
        ([...srcFiles.values()].reduce(
          (sum, r) => sum + (r.total > 0 ? r.hit / r.total : 1),
          0,
        ) /
          srcFiles.size) *
        100
      ).toFixed(1)
    : "100";
console.log(
  `Coverage gate PASSED — ${srcFiles.size} source files, avg ${avg}% line coverage (min ${MIN_LINE_COVERAGE * 100}% per file)`,
);
