/**
 * Build-time generator: reads @asyncapi/specs/bindings/ JSON Schemas
 * and generates src/constants/generated-bindings.ts with:
 *   - Protocol list (from directory names)
 *   - Binding versions per protocol
 *   - Placement matrix (which target kinds have binding definitions)
 *   - Field rules (type, enum, min, max per field per placement)
 *
 * Usage: bun run scripts/generate-binding-specs.ts
 *
 * This is the SINGLE SOURCE OF TRUTH for binding data. Hand-maintained
 * constants in binding-versions.ts and binding-field-validator.ts should
 * re-export or delegate to the generated values.
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const { join } = path;

const SPECS_DIR = join(process.cwd(), "node_modules/@asyncapi/specs/bindings");
const OUTPUT_FILE = join(process.cwd(), "src/constants/generated-bindings.ts");

const DIR_TO_KEY: Record<string, string> = {
  websockets: "ws",
};

const PLACEMENT_FILES = ["channel", "message", "operation", "server"] as const;

interface FieldRule {
  type: string;
  enum?: unknown[];
  min?: number;
  max?: number;
}

interface SchemaProperty {
  type?: string | string[];
  enum?: unknown[];
  minimum?: number;
  maximum?: number;
}

function toBindingKey(dirName: string): string {
  return DIR_TO_KEY[dirName] ?? dirName;
}

function sortVersions(versions: string[]): string[] {
  return [...versions].toSorted((a, b) => {
    const [aMajor, aMinor, aPatch] = a.split(".").map(Number);
    const [bMajor, bMinor, bPatch] = b.split(".").map(Number);
    return bMajor - aMajor || bMinor - aMinor || bPatch - aPatch;
  });
}

function extractFieldRules(
  schemaPath: string,
): Record<string, FieldRule> | null {
  if (!existsSync(schemaPath)) {
    return null;
  }

  const schema = JSON.parse(readFileSync(schemaPath, "utf8")) as {
    properties?: Record<string, SchemaProperty>;
  };

  const rules: Record<string, FieldRule> = {};
  if (!schema.properties) {
    return rules;
  }

  for (const [field, prop] of Object.entries(schema.properties)) {
    if (field === "bindingVersion") {
      continue;
    }
    const rule: FieldRule = { type: extractType(prop) };
    if (prop.enum) {
      rule.enum = prop.enum;
    }
    if (typeof prop.minimum === "number") {
      rule.min = prop.minimum;
    }
    if (typeof prop.maximum === "number") {
      rule.max = prop.maximum;
    }
    rules[field] = rule;
  }

  return rules;
}

function extractType(prop: SchemaProperty): string {
  if (!prop.type) {
    return "any";
  }
  if (Array.isArray(prop.type)) {
    return prop.type[0] ?? "any";
  }
  return prop.type;
}

function generate(): void {
  if (!existsSync(SPECS_DIR)) {
    console.error(`Specs directory not found: ${SPECS_DIR}`);
    process.exit(1);
  }

  const protocols = readdirSync(SPECS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .toSorted();

  const latestVersions: Record<string, string> = {};
  const allVersions: Record<string, string[]> = {};
  const placements: Record<string, Record<string, boolean>> = {};
  const fieldRules: Record<
    string,
    Record<string, Record<string, FieldRule>>
  > = {};

  for (const protoDir of protocols) {
    const key = toBindingKey(protoDir);
    const protoPath = join(SPECS_DIR, protoDir);
    const versions = readdirSync(protoPath, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name);

    const sorted = sortVersions(versions);
    latestVersions[key] = sorted[0] ?? "";
    allVersions[key] = sorted;

    const placement: Record<string, boolean> = {};
    const rules: Record<string, Record<string, FieldRule>> = {};
    const latestVersion = sorted[0] ?? "";
    const latestPath = join(protoPath, latestVersion);

    for (const p of PLACEMENT_FILES) {
      const exists = existsSync(join(latestPath, `${p}.json`));
      placement[p] = exists;
      if (exists) {
        const fr = extractFieldRules(join(latestPath, `${p}.json`));
        if (fr) {
          rules[p] = fr;
        }
      }
    }

    placements[key] = placement;
    fieldRules[key] = rules;
  }

  const lines: string[] = [
    "/**",
    " * AUTO-GENERATED by scripts/generate-binding-specs.ts",
    " * DO NOT EDIT MANUALLY — run: bun run scripts/generate-binding-specs.ts",
    " *",
    " * Source: @asyncapi/specs/bindings/ JSON Schemas",
    " */",
    "",
    `export const GENERATED_BINDING_PROTOCOLS = ${JSON.stringify(Object.keys(latestVersions).toSorted())} as const;`,
    "",
    `export const GENERATED_LATEST_VERSIONS: Record<string, string> = ${JSON.stringify(latestVersions, null, 2)};`,
    "",
    `export const GENERATED_ALL_VERSIONS: Record<string, string[]> = ${JSON.stringify(allVersions, null, 2)};`,
    "",
    `export const GENERATED_PLACEMENT: Record<string, Record<string, boolean>> = ${JSON.stringify(placements, null, 2)};`,
    "",
    `export const GENERATED_FIELD_RULES: Record<string, Record<string, Record<string, { type: string; enum?: unknown[]; min?: number; max?: number }>>> = ${JSON.stringify(fieldRules, null, 2)};`,
    "",
  ];

  writeFileSync(OUTPUT_FILE, lines.join("\n"));
  console.log(`Generated ${OUTPUT_FILE} (${protocols.length} protocols)`);
}

generate();
