/**
 * TypeSpec AsyncAPI Emitter - Minimal Working Entry Point
 */

import type { EmitContext } from "@typespec/compiler";
import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";

/**
 * Minimal AsyncAPI 3.0 emitter - generates basic specification
 */
export async function $onEmit(context: EmitContext) {
  // Basic output file from package.json options
  const outputFile = context.options["output-file"] || "asyncapi";
  const fileType = context.options["file-type"] || "yaml";
  const extension = fileType === "json" ? "json" : "yaml";
  
  // Generate minimal AsyncAPI 3.0 specification
  const asyncapiSpec = {
    asyncapi: "3.0.0",
    info: {
      title: "TypeSpec AsyncAPI",
      version: "1.0.0",
      description: "Generated by TypeSpec AsyncAPI Emitter"
    },
    servers: {
      development: {
        host: "localhost:9092",
        protocol: "kafka"
      }
    },
    channels: {},
    operations: {},
    components: {
      messages: {},
      schemas: {}
    }
  };

  // Write output file
  const outputPath = join(context.emitterOutputDir, `${outputFile}.${extension}`);
  const outputDir = dirname(outputPath);
  
  // Ensure directory exists
  mkdirSync(outputDir, { recursive: true });
  
  // Write the file
  const content = extension === "json" 
    ? JSON.stringify(asyncapiSpec, null, 2)
    : `asyncapi: 3.0.0
info:
  title: TypeSpec AsyncAPI
  version: 1.0.0
  description: Generated by TypeSpec AsyncAPI Emitter
servers:
  development:
    host: localhost:9092
    protocol: kafka
channels: {}
operations: {}
components:
  messages: {}
  schemas: {}`;
  
  writeFileSync(outputPath, content);
  
  console.log(`✅ Generated AsyncAPI specification: ${outputPath}`);
}