/**
 * Reference decorators for reusable components.
 *
 * Each decorator validates a non-empty string name via `validateNameAndRun`
 * and stores it as a reference. Generated by a shared factory.
 */

import type { DecoratorContext } from "@typespec/compiler";
import type { Type } from "@typespec/compiler";
import type { Program } from "@typespec/compiler";
import {
  storeBindingRef,
  storeCorrelationIdRef,
  storeMessageTraitRef,
  storeOperationTraitRef,
} from "./state-writers.js";
import { validateNameAndRun } from "./decorator-helpers.js";
import type { $lib } from "./lib.js";

type RefStore = (program: Program, target: Type, name: string) => void;

function makeUseDecorator(
  code: keyof typeof $lib.diagnostics,
  formatKey: string,
  store: RefStore,
): (context: DecoratorContext, target: Type, name: unknown) => void {
  return (context, target, name) => {
    validateNameAndRun({
      context,
      target,
      name,
      code,
      formatKey,
      onValid: (n) => { store(context.program, target, n); },
    });
  };
}

export const $useOperationTrait = makeUseDecorator("invalid-trait-config", "traitName", storeOperationTraitRef);
export const $useMessageTrait = makeUseDecorator("invalid-trait-config", "traitName", storeMessageTraitRef);
export const $useCorrelationId = makeUseDecorator("invalid-correlationId-config", "modelName", storeCorrelationIdRef);
export const $useBinding = makeUseDecorator("invalid-bindings-config", "targetKind", storeBindingRef);
